import type { Metadata } from "next";
import "./globals.css";
import { blMelody, inter } from "./fonts";
import NavBar from "./components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${blMelody.variable}`}
      >
        <header className="flex-none">
          <NavBar />
        </header>
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
