import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { blMelody, inter } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${blMelody.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
